[technote]
id = "DMTN-350"
series_id = "DMTN"
canonical_url = "https://dmtn-350.lsst.io"
github_url = "https://github.com/lsst-dm/dmtn-350"
github_default_branch = "main"
date_created = 2026-08-18T18:03:33Z
organization.name = "NSF-DOE Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

[[technote.authors]]
name.given = "Wei"
name.family = "Yang"
internal_id = "yangw"
orcid = "https://orcid.org/0009-0004-7733-8568"
[[technote.authors.affiliations]]
name = "SLAC National Accelerator Laboratory"
internal_id = "SLAC"
address = "Menlo Park"
